### ISSUE TITLE
[Bug]: mod causing world/server deadlock (overtick/freeze)

### ISSUE THREAD

**Issue by VaporeonScripts** [Fuzss/fastitemframes#1]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

latest possible

### Minimal Setup (Required)

Yes

### Notes (Required)

total freeze (entities, item,unable to open containers)

### latest.log (Required)

https://mclo.gs/z477Wuw

**Comment by Fuzss** [comment]
Please report this to C2ME.

```
"Server thread" prio=4 Id=211 TIMED_WAITING on java.lang.String@443b1e6a
--
14125 | at java.base@21.0.6/jdk.internal.misc.Unsafe.park(Native Method)
14126 | -  waiting on java.lang.String@443b1e6a
14127 | at java.base@21.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
14128 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:521)
14129 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133)
14130 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.managedBlock(ServerChunkCache.java:533)
14131 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.mixinextras$bridge$managedBlock$94(ServerChunkCache.java)
14132 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$$Lambda/0x000072261c4efc68.call(Unknown Source)
14133 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.wrapOperation$gem000$c2me_base$instrumentAwaitChunk(ServerChunkCache.java:5632)
14134 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:2250)
14135 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunk$mixinextras$wrapped$97(ServerChunkCache.java:2171)
14136 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.mixinextras$bridge$getChunk$mixinextras$wrapped$97$98(ServerChunkCache.java)
14137 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$$Lambda/0x000072261c4cd7f0.call(Unknown Source)
14138 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.wrapMethod$gem000$c2me_base$instrumentGetChunk(ServerChunkCache.java:5646)
14139 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java)
14140 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getChunk(Level.java:202)
14141 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getChunk(Level.java:6329)
14142 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getBlockState(Level.java:6821)
14143 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.LevelReader.isEmptyBlock(LevelReader.java:87)
14144 | at TRANSFORMER/fastitemframes@21.1.0/fuzs.fastitemframes.handler.ItemFrameHandler.onEntityLoad(ItemFrameHandler.java:43)
14145 | at TRANSFORMER/fastitemframes@21.1.0/fuzs.fastitemframes.FastItemFrames$$Lambda/0x00007226162c5378.onEntityLoad(Unknown Source)
14146 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl.lambda$registerEventHandlers$65(NeoForgeEventInvokerRegistryImpl.java:442)
14147 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl$$Lambda/0x000072261b78c6a8.accept(Unknown Source)
14148 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.api.event.v1.core.NeoForgeEventInvokerRegistry.lambda$register$0(NeoForgeEventInvokerRegistry.java:31)
14149 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.api.event.v1.core.NeoForgeEventInvokerRegistry$$Lambda/0x0000722611e23228.accept(Unknown Source)
14150 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl$ForgeEventInvoker.lambda$register$1(NeoForgeEventInvokerRegistryImpl.java:784)
14151 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl$ForgeEventInvoker$$Lambda/0x0000722611ec1bd8.accept(Unknown Source)
14152 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler$WithPredicate.invoke(ConsumerEventHandler.java:47)
14153 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
14154 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
14155 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntity(PersistentEntitySectionManager.java:79)
14156 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$addWorldGenChunkEntities$1(PersistentEntitySectionManager.java:121)
14157 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager$$Lambda/0x000072261cd231d0.accept(Unknown Source)
14158 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$0(EntityType.java:1156)
14159 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1$$Lambda/0x000072261cd23620.apply(Unknown Source)
14160 | at java.base@21.0.6/java.util.Optional.map(Unknown Source)
14161 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:1134)
14162 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$1(EntityType.java:1155)
14163 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1$$Lambda/0x000072261cd233f8.accept(Unknown Source)
14164 | at java.base@21.0.6/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
14165 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:1155)
14166 | at java.base@21.0.6/java.util.Spliterator.forEachRemaining(Unknown Source)
14167 | at java.base@21.0.6/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
14168 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addWorldGenChunkEntities(PersistentEntitySectionManager.java:120)
14169 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.addWorldGenChunkEntities(ServerLevel.java:1655)
14170 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible.lambda$toFullChunk$1(ServerAccessible.java:77)
14171 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible$$Lambda/0x000072261cb83b10.run(Unknown Source)
14172 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:480)
14173 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible.lambda$upgradeToThis$0(ServerAccessible.java:56)
14174 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible$$Lambda/0x000072261c5e01f8.run(Unknown Source)
14175 | at java.base@21.0.6/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
14176 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
14177 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:559)
14178 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
14179 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:568)
14180 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
14181 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.managedBlock(ServerChunkCache.java:533)
14182 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.mixinextras$bridge$managedBlock$94(ServerChunkCache.java)
14183 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$$Lambda/0x000072261c4efc68.call(Unknown Source)
14184 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.wrapOperation$gem000$c2me_base$instrumentAwaitChunk(ServerChunkCache.java:5632)
14185 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:2250)
14186 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunk$mixinextras$wrapped$97(ServerChunkCache.java:2171)
14187 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.mixinextras$bridge$getChunk$mixinextras$wrapped$97$98(ServerChunkCache.java)
14188 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$$Lambda/0x000072261c4cd7f0.call(Unknown Source)
14189 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.wrapMethod$gem000$c2me_base$instrumentGetChunk(ServerChunkCache.java:5646)
14190 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java)
14191 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getChunk(Level.java:202)
14192 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getChunk(Level.java:6329)
14193 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getBlockState(Level.java:6821)
14194 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.LevelReader.isEmptyBlock(LevelReader.java:87)
14195 | at TRANSFORMER/fastitemframes@21.1.0/fuzs.fastitemframes.handler.ItemFrameHandler.onEntityLoad(ItemFrameHandler.java:43)
14196 | at TRANSFORMER/fastitemframes@21.1.0/fuzs.fastitemframes.FastItemFrames$$Lambda/0x00007226162c5378.onEntityLoad(Unknown Source)
14197 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl.lambda$registerEventHandlers$65(NeoForgeEventInvokerRegistryImpl.java:442)
14198 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl$$Lambda/0x000072261b78c6a8.accept(Unknown Source)
14199 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.api.event.v1.core.NeoForgeEventInvokerRegistry.lambda$register$0(NeoForgeEventInvokerRegistry.java:31)
14200 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.api.event.v1.core.NeoForgeEventInvokerRegistry$$Lambda/0x0000722611e23228.accept(Unknown Source)
14201 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl$ForgeEventInvoker.lambda$register$1(NeoForgeEventInvokerRegistryImpl.java:784)
14202 | at TRANSFORMER/puzzleslib@21.1.28/fuzs.puzzleslib.neoforge.impl.event.NeoForgeEventInvokerRegistryImpl$ForgeEventInvoker$$Lambda/0x0000722611ec1bd8.accept(Unknown Source)
14203 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler$WithPredicate.invoke(ConsumerEventHandler.java:47)
14204 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
14205 | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
14206 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntity(PersistentEntitySectionManager.java:79)
14207 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$addWorldGenChunkEntities$1(PersistentEntitySectionManager.java:121)
14208 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager$$Lambda/0x000072261cd231d0.accept(Unknown Source)
14209 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$0(EntityType.java:1156)
14210 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1$$Lambda/0x000072261cd23620.apply(Unknown Source)
14211 | at java.base@21.0.6/java.util.Optional.map(Unknown Source)
14212 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:1134)
14213 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$1(EntityType.java:1155)
14214 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1$$Lambda/0x000072261cd233f8.accept(Unknown Source)
14215 | at java.base@21.0.6/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
14216 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:1155)
14217 | at java.base@21.0.6/java.util.Spliterator.forEachRemaining(Unknown Source)
14218 | at java.base@21.0.6/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
14219 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addWorldGenChunkEntities(PersistentEntitySectionManager.java:120)
14220 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.addWorldGenChunkEntities(ServerLevel.java:1655)
14221 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible.lambda$toFullChunk$1(ServerAccessible.java:77)
14222 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible$$Lambda/0x000072261cb83b10.run(Unknown Source)
14223 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:480)
14224 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible.lambda$upgradeToThis$0(ServerAccessible.java:56)
14225 | at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0+alpha.0.58+1.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.ServerAccessible$$Lambda/0x000072261c5e01f8.run(Unknown Source)
14226 | at java.base@21.0.6/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
14227 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
14228 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:559)
14229 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
14230 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:568)
14231 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:275)
14232 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:860)
14233 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849)
14234 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111)
14235 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:825)
14236 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712)
14237 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
14238 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer$$Lambda/0x000072261c254ac0.run(Unknown Source)
14239 | at java.base@21.0.6/java.lang.Thread.runWith(Unknown Source)
14240 | at java.base@21.0.6/java.lang.Thread.run(Unknown Source)


```

**Comment by VaporeonScripts** [comment]
this only happens with ur mod installed btw, but ig its some kind of incompat, ill report it right now!

**Comment by Fuzss** [comment]
Should be fixed on my end actually now.

**Comment by UnnamedWei** [comment]
> Should be fixed on my end actually now.

I am using the newest version of this mod and still encountered this issue, are you sure about the fixing?

**Comment by Fuzss** [comment]
Please open a new issue and provide logs + crash-report.

**Comment by UnnamedWei** [comment]
> 请打开一个新问题并提供日志+崩溃报告。

There is no crash report, just the server deadlock for few minutes but not crashing the server, we updated the puzzlelibs and installed the FastItemFrame, there is also an issue about network usage spikes, high internet usage with not that much players.

**Comment by UnnamedWei** [comment]
> 请打开一个新问题并提供日志+崩溃报告。

https://github.com/Tiviacz1337/Travelers-Backpack/issues/1247#issuecomment-2777502844

**Comment by UnnamedWei** [comment]
> 请打开一个新问题并提供日志+崩溃报告。

I will try to upload the logs later in a new issue

**Comment by Fuzss** [comment]
Thanks. Ideally also include a Spark Report then if there is no crash.
